### ISSUE TITLE
Not able to switch Speakers

### ISSUE THREAD

**Issue by sanketns** [livekit/client-sdk-swift#159]
Not able to switch/(On or Off) between ear speaker and bottom speaker using AudioManager.shared.preferSpeakerOutput property. Tried every possible way to achieve this but no luck.
Kindly guide for the same.

**Comment by hiroshihorie** [comment]
Hi, I'm working on this issue.

**Comment by hiroshihorie** [comment]
Update:
Looks like some things broke around AVAudioSession on iOS 16.

Related:
https://developer.apple.com/forums/thread/717621
https://stackoverflow.com/questions/73349619/ios-16-beta-5-avaudiosession-setcategory-produces-strange-error-what

**Comment by sanketns** [comment]
It's not working on ios 16 earlier devices. Tried on Device having (iOS 15.0.1)

**Comment by hiroshihorie** [comment]
Trying to resolve a bunch of audio related issues, it might take some time.

**Comment by hiroshihorie** [comment]
I think the fix merged in `main` should fix it.

**Comment by sanketns** [comment]
It worked using packages, Thanks for the support.

**Comment by sanketns** [comment]
Still having one issue, Not able to switch back to normal phone speaker while connected with a bluetooth speaker.

**Comment by davidzhao** [comment]
I believe this is expected. iOS priorities BT for audio output.

**Comment by sanketns** [comment]
I agree with the IOS priorities BT thing. But i guess, while switching to the normal speaker while connected to bluetooth device. The code in AudioManager overrides the selection and the configuration stays as it is. It does not take affect because of this. Could you please double check that code in AudioManager and find any possible way for this. 

Thank you

**Comment by hiroshihorie** [comment]
Hey I will take a look.

**Comment by sanketns** [comment]
@hiroshihorie , did you find any solution for this issue?

Issue -> "Not able to switch back to normal speaker mode if connected with bluetooth earphones"

**Comment by hiroshihorie** [comment]
Hi, I was recently thinking about what's the best practice for this issue.

Originally, I introduced `AudioManager.shared.preferSpeakerOutput` (default: true) to support use cases such as a 1 to 1 phone call, using the receiver instead of speaker (`preferSpeakerOutput`: false).

Now this is causing confusion because it is not capable of forcing speaker output when a Bluetooth device is connected (which I did not intend at first). The name `preferSpeakerOutput` is misleading and I'm thinking of renaming it or documenting it well.

I believe it is indented behavior to switch to the bluetooth device when it's connected. Looks like Apple prefers the user to have control through the control center or by invoking a `AVRoutePickerView`.

According to Apple:
> The preferred method for routing audio to the speaker instead of the receiver for speakerphone functionality is through the use of the [Media Player](https://developer.apple.com/documentation/mediaplayer) framework’s [MPVolumeView](https://developer.apple.com/documentation/mediaplayer/mpvolumeview) class.

(https://developer.apple.com/documentation/avfaudio/avaudiosession/1616443-overrideoutputaudioport)

Testing with example app:
<img src="https://user-images.githubusercontent.com/548776/214074440-a9424e26-663a-469d-b7a7-c5c010db8589.PNG" width="250" />

I will try to provide methods for easily invoking the device picker (https://github.com/livekit/client-sdk-swift/commit/5dae72386ca0e46633ba0175de392be22fad52a8).

Would like to hear any opinions (@sanketns).

I will close this for now.
