### ISSUE TITLE
Replace dispatch queue based locking with os_unfair_lock

### ISSUE THREAD

**Issue by ronnyf** [livekit/client-sdk-swift#192]
Using os_unfair_lock/unlock is an order of magnitude faster than dispatch_async when the resource is not heavily contended. 
I am providing a reference implementation where I am keeping the value in a CurrentValueSubject to facilitate subscribing to value changes with Combine. This might come in handy later. 

The issue with concurrent queues is that they can lead to thread explosions and they are not entirely cheap either. An unfair lock is an excellent tool to increase efficiency without changes to any dependency.

**Comment by hiroshihorie** [comment]
Thanks @ronnyf for your advice, I'm not sure how much of a performance gain there is to rewrite since most of the heavy computation is done on the WebRTC side.

I could do a experimental re-write of the StateSync class to use os_unfair_lock, but I'm not sure if there will be a noticeable overall performance gain.

**Comment by ronnyf** [comment]
Sorry I missed this notification. Let me take a look and report back.

**Comment by hiroshihorie** [comment]
State lock is now using os_unfair_lock so I will close this.
