### ISSUE TITLE
CocoaPods version

### ISSUE THREAD

**Issue by patryk-sredzinski** [livekit/client-sdk-swift#479]
Can we have latest LiveKit uploaded to CocoaPods?
Current newest version is 2.0.12

Is there any way to automate this on every release?

**Comment by hiroshihorie** [comment]
Hi, 2.0.14 has been published but I think we will stop publishing new pods eventually.
Please consider migrating to SPM instead of CocoaPods https://blog.cocoapods.org/CocoaPods-Support-Plans/
Our dependencies for example, [Logging](https://cocoapods.org/pods/Logging) package is not being published on pods anymore.
The pod publish workflow is hacky and I had to copy libs from Xcode14.2 into Xcode15.4 for it to pass validation etc.
A lot of things break with pods so I think I need to manually test each release, that's why I'm not so interested in automating this.

**Comment by patryk-sredzinski** [comment]
Thank you @hiroshihorie 

I totally get it and I would love to migrate my project to SPM, although with so many dependencies I have there are dependencies that aren't on SPM, and having 2 separate dependency managers will be a pain to use.

I would really like to get this updated as long as possible. But I'll log myself a ticket to check if I can switch to SPM :)
Thanks for all the effort you do!

**Comment by tamimattafi** [comment]
@hiroshihorie Hello!
Is there a possibility to use your GitHub as a repository for CocoaPods instead of the main repository? I believe this will be easier for you to publish new versions than using the Specs repository.

Many projects still depend on CocoaPods and migration requires a lot of time and efforts, which are not always affordable by some businesses.

For the GitHub part, we tried adding `LiveKitClient` and directly point to your repository like this:
```v
pod 'LiveKitClient', :git => 'https://github.com/livekit/client-sdk-swift.git', :tag => '2.0.17'
```
But during `pod install`, it can't find `LiveKitWebRTC (= 125.6422.11)`, so we added it as well like this:
```v
pod 'LiveKitWebRTC', :git => 'https://github.com/livekit/webrtc-xcframework.git', :tag => '125.6422.11'
```
The installation now completes successfully. But compilation fails since some source code can't find `module LiveKitWebRTC`. 

It seems like if you update the `podspec` file to point to `LiveKitWebRTC` dependency using `git` URL and tag, it will automatically find it and link it to the project. Maybe the same is needed with some other dependencies.
