### ISSUE TITLE
How to broadcast audio from device instead of microphone

### ISSUE THREAD

**Issue by phannguyenvn** [livekit/client-sdk-swift#5]
My app will allow users to create an online karaoke room.
When the user is singing, I want background music and their voice to be played to all participants in that room.
I don't know how to configure Webrtc to receive audio from the device and processed vocals.

Thanks,

**Comment by davidzhao** [comment]
Do you have access to the music files that you'd want to play? If so, this should be possible. (but might require us to expose more APIs via the SDK)

If you are thinking about capturing music from another app, that's disallowed by iOS.

Can you share more?

**Comment by phannguyenvn** [comment]
Hi Davidzhao,

Thank you for responding.

Yes, I have full access to my music file, I can play the music file through AVAudioPlayer in my app.

Besides streaming voice from the microphone, do we also stream music?

There are some online KTV karaoke apps that do this like Smule, Starmaker...

please help me, thanks

**Comment by davidzhao** [comment]
I understand now. There are two ways to go about this.

1. use our [Go Server SDK] from the server side to publish the music file to the room, all participants will receive it and sing along. (you can do this today).
2. decode the audio file and publish it as an additional audio track. though you can't do this yet because:
    * iOS SDK doesn't support non-microphone audio sources today. we'd want to build this in the future, but just don't have cycles right now. We'd welcome contributions though!
